### ISSUE TITLE
tried the simple example and got the following error:

### ISSUE THREAD

**Issue by wangping25** [dato-code/rpsclient#1]
This example
------------------
x <- 1 
y <- 2
subtract_private <- function(a) { return(a-1)}
subtract <- function(a) { return(subtract_private(a) - x - y)}
rpsclient::deploy(ps,"subtract",subtract)

Got this error:
--------------------
> rpsclient::deploy(ps,"subtract",subtract)
Error in grep("^[a-zA-Z0-9_ -]+$", model_name) : 
  object 'model_name' not found

**Comment by esoroush** [comment]
this issue is addressed.
